# action.yml
name: 'Slack Notification'
description: 'Notify slack of something'
inputs:
  repository-name:
    description: 'The name of the GitHub repository'
    required: true
  github-token:
    description: 'The GitHub token to access private repositories'
    required: true
  github-ref:
    description: 'The release version in the form refs/tags/v4'
    required: true
  slack-hook:
    description: 'The slack webhook url'
    required: true
  outcome:
    description: 'The outcome of the job to be release to notify about'
    required: false
    default: 'false'
  notification-type:
    description: 'The type of notification (release, terraform)'
    required: false
  pr-number:
    description: 'The PR number for terraform notifications'
    required: false
  output:
    description: 'The terraform output content (supports base64 encoding)'
    required: false
  action-type:
    description: 'The terraform action type (PLAN, APPLY, etc.)'
    required: false
  gcp-environment:
    description: 'The GCP environment name (e.g., dev, staging, prod)'
    required: false
  run-id:
    description: 'The GitHub Actions run ID'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INPUT_REPOSITORY_NAME: ${{ inputs.repository-name }}
    INPUT_GITHUB_TOKEN: ${{ inputs.github-token }}
    INPUT_GITHUB_REF: ${{ inputs.github-ref }}
    INPUT_SLACK_HOOK: ${{ inputs.slack-hook }}
    INPUT_OUTCOME: ${{ inputs.outcome || 'false' }}
    INPUT_NOTIFICATION_TYPE: ${{ inputs.notification-type }}
    INPUT_PR_NUMBER: ${{ inputs.pr-number }}
    INPUT_OUTPUT: ${{ inputs.output }}
    INPUT_ACTION_TYPE: ${{ inputs.action-type }}
    INPUT_GCP_ENVIRONMENT: ${{ inputs.gcp-environment }}
    INPUT_RUN_ID: ${{ inputs.run-id || github.run_id }}