# action.yml
name: 'Slack Notification'
description: 'Notify slack of something'
inputs:
  repository-name:
    description: 'The name of the GitHub repository'
    required: true
  github-token:
    description: 'The GitHub token to access private repositories'
    required: true
  github-ref:
    description: 'The release version in the form refs/tags/v4'
    required: true
  slack-hook:
    description: 'The slack webhook url'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - ${{ inputs.repository-name }}
  - ${{ inputs.github-token }}
  - ${{ inputs.github-ref }}
  - ${{ inputs.slack-hook }}